# Generated by Django 3.2.7 on 2021-09-26 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=150, unique=True, verbose_name='Codigo')),
                ('descripcion', models.TextField(max_length=500, verbose_name='Descripcion')),
                ('fecha', models.DateField(verbose_name='Fecha Creacion Documento')),
                ('tipo', models.CharField(max_length=150, verbose_name='Tipo de Documento')),
                ('version', models.CharField(max_length=150, unique=True, verbose_name='Version')),
            ],
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreclave', models.CharField(max_length=150, unique=True, verbose_name='Nombre clave del proyecto')),
                ('denominacioncomercial', models.CharField(choices=[('ventas', 'ventas'), ('tecnologia', 'tecnologia')], max_length=150, verbose_name='Denominacion Comercial')),
                ('fechainicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fechafinalizacion', models.DateField(verbose_name='Fecha de final')),
                ('estadoactual', models.CharField(choices=[('NoIniciado', 'NoIniciado'), ('Comenzo', 'Comenzo'), ('Finalizado', 'Finalizado')], default='NoIniciado', max_length=150)),
                ('promotor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoEmpleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleados', djongo.models.fields.ArrayReferenceField(blank=True, null=True, on_delete=djongo.models.fields.ArrayReferenceField._on_delete, related_name='empleados', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='proyectos.proyectos', verbose_name='Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriasUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacionhistoriausuario', models.CharField(max_length=150, unique=True, verbose_name='Codigo')),
                ('descripcionhistoriausuario', models.TextField(max_length=500, verbose_name='Descripcion')),
                ('fechainicioesperado', models.DateField(blank=True, null=True, verbose_name='Fecha Inicio Esperado')),
                ('fechainicioreal', models.DateField(blank=True, null=True, verbose_name='Fecha Inicio Real')),
                ('duracionesperada', models.DateField(blank=True, null=True, verbose_name='Duracion Estimada')),
                ('duracionreal', models.DateField(blank=True, null=True, verbose_name='Duracion Real')),
                ('documentacion', djongo.models.fields.ArrayReferenceField(blank=True, null=True, on_delete=djongo.models.fields.ArrayReferenceField._on_delete, related_name='documentacion', to='proyectos.documentacion')),
                ('empleados', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyectos', verbose_name='Proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='documentacion',
            name='proyecto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='proyectos.proyectos', verbose_name='Proyecto'),
        ),
    ]
