# Generated by Django 3.2.7 on 2021-09-25 21:45

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='tareas',
            field=djongo.models.fields.ArrayReferenceField(blank=True, null=True, on_delete=djongo.models.fields.ArrayReferenceField._on_delete, related_name='Tusuario', to='proyectos.historiasusuario'),
        ),
    ]
