# Generated by Django 3.2.7 on 2021-09-25 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoEmpleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleados', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Empleados')),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='proyectos.proyectos', verbose_name='Proyecto')),
            ],
        ),
    ]
